services:
  db:
    image: postgres:16-alpine
    container_name: esport_db
    environment:
      POSTGRES_USER: esport_user
      POSTGRES_PASSWORD: esport_pass
      POSTGRES_DB: esport_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esport_user -d esport_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
